package com.privatechain.access.invite;

import java.time.Instant;
import java.util.Base64;
import java.util.Objects;

/**
 * Immutable representation of a signed, time-limited invitation token.
 *
 * <p>An invitation token is generated by an admin node via {@link InvitationService}
 * and presented by a new node during onboarding. The token contains:
 * <ul>
 *   <li>The requested node ID</li>
 *   <li>An expiry timestamp (epoch seconds)</li>
 *   <li>An ECDSA signature over the {@code nodeId || expiry} payload, signed by the admin's private key</li>
 * </ul>
 *
 * <p>Once the token is accepted and the signature verified, the node ID is added
 * to the allowlist and assigned a default role by the {@link InvitationService}.</p>
 *
 * <h2>Immutability</h2>
 * All fields are immutable and final. Once created, a token cannot be modified.
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * InvitationToken token = InvitationToken.create(nodeId, expiryEpoch, signature);
 * String encoded = token.getEncodedToken();  // Base64 for transmission
 * // ...
 * InvitationToken parsed = InvitationToken.parseEncodedToken(encoded);
 * if (parsed.isExpired()) {
 *     reject();
 * }
 * }</pre>
 *
 * @see InvitationService
 * @since 1.0.0
 */
public final class InvitationToken {

    // ─── Fields ───────────────────────────────────────────────────────────────

    /**
     * The node ID being invited and to be added to the allowlist.
     */
    private final String nodeId;

    /**
     * The token expiry time as epoch seconds (Unix timestamp).
     * After this instant, the token is invalid and must be rejected.
     */
    private final long expiryEpochSeconds;

    /**
     * The ECDSA signature over the {@code nodeId || expiryEpochSeconds} concatenation,
     * signed by the admin node's private key. DER-encoded, typically 70-72 bytes.
     */
    private final byte[] signature;

    // ─── Constructor ──────────────────────────────────────────────────────────

    /**
     * Private constructor; use factory methods instead.
     *
     * @param nodeId               the node ID being invited (non-null)
     * @param expiryEpochSeconds   the expiry time in Unix epoch seconds (positive)
     * @param signature            the ECDSA signature (non-null, non-empty)
     */
    private InvitationToken(String nodeId, long expiryEpochSeconds, byte[] signature) {
        this.nodeId = nodeId;
        this.expiryEpochSeconds = expiryEpochSeconds;
        this.signature = signature;
    }

    // ─── Factory methods ──────────────────────────────────────────────────────

    /**
     * Creates a new invitation token with the given parameters.
     *
     * <p>This factory is normally called by {@link InvitationService} after signing
     * the payload.</p>
     *
     * @param nodeId             the node ID being invited (non-null, non-blank)
     * @param expiryEpochSeconds the expiry time in Unix epoch seconds (must be positive)
     * @param signature          the ECDSA signature bytes (non-null, non-empty)
     * @return a new {@code InvitationToken}
     * @throws NullPointerException     if any parameter is null
     * @throws IllegalArgumentException if nodeId is blank, expiryEpochSeconds is non-positive,
     *                                  or signature is empty
     */
    public static InvitationToken create(String nodeId, long expiryEpochSeconds, byte[] signature) {
        Objects.requireNonNull(nodeId, "nodeId must not be null");
        Objects.requireNonNull(signature, "signature must not be null");
        if (nodeId.isBlank()) {
            throw new IllegalArgumentException("nodeId must not be blank");
        }
        if (expiryEpochSeconds <= 0) {
            throw new IllegalArgumentException("expiryEpochSeconds must be positive");
        }
        if (signature.length == 0) {
            throw new IllegalArgumentException("signature must not be empty");
        }
        return new InvitationToken(nodeId, expiryEpochSeconds, signature.clone());
    }

    /**
     * Parses an encoded invitation token (Base64-formatted) back into its components.
     *
     * <p>The token is expected to be in the format produced by {@link #getEncodedToken()}.
     * This is a convenience method for deserialization; the actual signature verification
     * is performed by {@link InvitationService#verifyToken(InvitationToken)}.</p>
     *
     * @param encodedToken the Base64-encoded token string (non-null, non-blank)
     * @return a parsed {@code InvitationToken}
     * @throws NullPointerException     if encodedToken is null
     * @throws IllegalArgumentException if encodedToken is blank or malformed
     */
    public static InvitationToken parseEncodedToken(String encodedToken) {
        Objects.requireNonNull(encodedToken, "encodedToken must not be null");
        if (encodedToken.isBlank()) {
            throw new IllegalArgumentException("encodedToken must not be blank");
        }

        try {
            byte[] decodedBytes = Base64.getDecoder().decode(encodedToken);
            // Structure: [nodeId length (4 bytes)] [nodeId UTF-8] [expiryEpochSeconds (8 bytes)] [signature]
            if (decodedBytes.length < 12) {
                throw new IllegalArgumentException("token is too short");
            }

            int nodeIdLength = bytesToInt(decodedBytes, 0);
            if (nodeIdLength <= 0 || nodeIdLength > decodedBytes.length - 12) {
                throw new IllegalArgumentException("malformed token: invalid nodeId length");
            }

            String nodeId = new String(decodedBytes, 4, nodeIdLength, java.nio.charset.StandardCharsets.UTF_8);
            int expiryOffset = 4 + nodeIdLength;
            long expiryEpochSeconds = bytesToLong(decodedBytes, expiryOffset);

            byte[] signature = new byte[decodedBytes.length - (expiryOffset + 8)];
            System.arraycopy(decodedBytes, expiryOffset + 8, signature, 0, signature.length);

            return create(nodeId, expiryEpochSeconds, signature);

        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("token decoding failed: " + e.getMessage(), e);
        }
    }

    // ─── Accessors ────────────────────────────────────────────────────────────

    /**
     * Returns the invited node ID.
     *
     * @return the node ID that will be added to the allowlist upon token acceptance
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Returns the token expiry time as Unix epoch seconds.
     *
     * @return epoch seconds timestamp
     */
    public long getExpiryEpochSeconds() {
        return expiryEpochSeconds;
    }

    /**
     * Returns the expiry time as an {@link Instant}.
     *
     * @return expiry as an instant
     */
    public Instant getExpiryInstant() {
        return Instant.ofEpochSecond(expiryEpochSeconds);
    }

    /**
     * Returns the ECDSA signature bytes (DER-encoded).
     *
     * <p>The returned array is a copy; modifications do not affect the token.</p>
     *
     * @return the signature bytes
     */
    public byte[] getSignature() {
        return signature.clone();
    }

    /**
     * Encodes this token as a Base64 string suitable for transmission or storage.
     *
     * <p>The encoded format is: {@code [nodeId length (4 bytes)] + [nodeId (UTF-8)] +
     * [expiryEpochSeconds (8 bytes)] + [signature bytes]}, then Base64-encoded.</p>
     *
     * @return Base64-encoded token string
     */
    public String getEncodedToken() {
        byte[] nodeIdBytes = nodeId.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        int totalLength = 4 + nodeIdBytes.length + 8 + signature.length;

        byte[] tokenBytes = new byte[totalLength];
        int offset = 0;

        // Write nodeId length (4 bytes, big-endian)
        intToBytes(nodeIdBytes.length, tokenBytes, offset);
        offset += 4;

        // Write nodeId
        System.arraycopy(nodeIdBytes, 0, tokenBytes, offset, nodeIdBytes.length);
        offset += nodeIdBytes.length;

        // Write expiryEpochSeconds (8 bytes, big-endian)
        longToBytes(expiryEpochSeconds, tokenBytes, offset);
        offset += 8;

        // Write signature
        System.arraycopy(signature, 0, tokenBytes, offset, signature.length);

        return Base64.getEncoder().encodeToString(tokenBytes);
    }

    /**
     * Checks whether this token has expired.
     *
     * @return {@code true} if the current time is past the token's expiry time
     */
    public boolean isExpired() {
        return System.currentTimeMillis() > expiryEpochSeconds * 1000L;
    }

    /**
     * Returns the payload that was signed: {@code nodeId || expiryEpochSeconds}.
     *
     * <p>This is used by {@link InvitationService#verifyToken(InvitationToken)}
     * to verify the signature against the admin's public key.</p>
     *
     * @return raw bytes of the signed payload
     */
    byte[] getSignableBytes() {
        byte[] nodeIdBytes = nodeId.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        byte[] payload = new byte[nodeIdBytes.length + 8];
        System.arraycopy(nodeIdBytes, 0, payload, 0, nodeIdBytes.length);
        longToBytes(expiryEpochSeconds, payload, nodeIdBytes.length);
        return payload;
    }

    // ─── Object overrides ─────────────────────────────────────────────────────

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof InvitationToken other)) {
            return false;
        }
        return Objects.equals(nodeId, other.nodeId)
            && expiryEpochSeconds == other.expiryEpochSeconds
            && java.util.Arrays.equals(signature, other.signature);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        return Objects.hash(nodeId, expiryEpochSeconds, java.util.Arrays.hashCode(signature));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return "InvitationToken{" +
            "nodeId='" + nodeId + '\'' +
            ", expiryEpochSeconds=" + expiryEpochSeconds +
            ", signatureLength=" + signature.length +
            '}';
    }

    // ─── Internal encoding helpers ────────────────────────────────────────────

    /**
     * Converts a 4-byte big-endian sequence to an integer.
     */
    private static int bytesToInt(byte[] bytes, int offset) {
        return ((bytes[offset] & 0xFF) << 24)
            | ((bytes[offset + 1] & 0xFF) << 16)
            | ((bytes[offset + 2] & 0xFF) << 8)
            | (bytes[offset + 3] & 0xFF);
    }

    /**
     * Converts an 8-byte big-endian sequence to a long.
     */
    private static long bytesToLong(byte[] bytes, int offset) {
        return ((long) (bytes[offset] & 0xFF) << 56)
            | ((long) (bytes[offset + 1] & 0xFF) << 48)
            | ((long) (bytes[offset + 2] & 0xFF) << 40)
            | ((long) (bytes[offset + 3] & 0xFF) << 32)
            | ((long) (bytes[offset + 4] & 0xFF) << 24)
            | ((long) (bytes[offset + 5] & 0xFF) << 16)
            | ((long) (bytes[offset + 6] & 0xFF) << 8)
            | (bytes[offset + 7] & 0xFF);
    }

    /**
     * Writes an integer to a 4-byte big-endian sequence.
     */
    private static void intToBytes(int value, byte[] bytes, int offset) {
        bytes[offset] = (byte) ((value >> 24) & 0xFF);
        bytes[offset + 1] = (byte) ((value >> 16) & 0xFF);
        bytes[offset + 2] = (byte) ((value >> 8) & 0xFF);
        bytes[offset + 3] = (byte) (value & 0xFF);
    }

    /**
     * Writes a long to an 8-byte big-endian sequence.
     */
    private static void longToBytes(long value, byte[] bytes, int offset) {
        bytes[offset] = (byte) ((value >> 56) & 0xFF);
        bytes[offset + 1] = (byte) ((value >> 48) & 0xFF);
        bytes[offset + 2] = (byte) ((value >> 40) & 0xFF);
        bytes[offset + 3] = (byte) ((value >> 32) & 0xFF);
        bytes[offset + 4] = (byte) ((value >> 24) & 0xFF);
        bytes[offset + 5] = (byte) ((value >> 16) & 0xFF);
        bytes[offset + 6] = (byte) ((value >> 8) & 0xFF);
        bytes[offset + 7] = (byte) (value & 0xFF);
    }
}

